- type: job
  id: CentralCommandOfficial
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcomGear
  icon: "Nanotrasen"
  supervisors: job-supervisors-hos
  canBeAntag: false
  accessGroups:
  - AllAccess

- type: startingGear
  id: CentcomGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatCentcom
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
    id: CentcomPDA
    ears: ClothingHeadsetAltCommand
    pocket1: PaperOffice
    pocket2: PenCentcom
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
