- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # Corvax-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # Corvax-RoleTime
      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "SecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecGrey # Corvax-Resprite
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    outerClothing: ClothingOuterArmorBasic
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraSportsAlternative # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerclothingskirt: ClothingUniformJumpskirtColorRed
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
