- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10800 #3 hrs
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
<<<<<<< HEAD
    back: ClothingBackpackPsychologistFilled # Corvax-Stamp
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraSports # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtPsychologist # Corvax-Resprite
  satchel: ClothingBackpackSatchelPsychologistFilled # Corvax-Stamp
  duffelbag: ClothingBackpackDuffelPsychologistFilled # Corvax-Stamp
=======
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - BoxSurvivalMedical
>>>>>>> 24e7653c984da133283457da2089e629161a7ff2
