- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - External
  extendedAccess:
  - Salvage

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelCargoFilled
  duffelbag: ClothingBackpackDuffelCargoFilled
