- type: job
  id: Magistrat
  name: job-name-magistrat
  description: job-description-magistrat
  playTimeTracker: JobMagistrat
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 600000
    # - !type:DepartmentTimeRequirement
    #   department: Sponsor
    #   time: 10
  startingGear: MagistratGear
  icon: "JobIconMagistrat"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Maintenance
    - Service
    - Security
    - Magistrate
    - LawyerDepartament
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MagistratGear
  equipment:
    jumpsuit: ADTClothingUniformsJumpsuitWhiteDiplomatSuitL
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesBootsLaceup
    #mask: Ну что за косипор оставляет пустуе значения?
    #outerClothing: ClothingOuterRobesJudge
    eyes: ClothingEyesGlassesSunglasses
    #head: ClothingHeadHatPwig
    id: MagistratPDA
    #gloves:
    ears: ClothingHeadsetMagistrat
    #belt:
    neck: ClothingNeckLawyerbadge
    pocket1: RubberStampMagistrat
    pocket2: ADTtelescopicBaton
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ADTClothingUniformsJumpsuitWhiteDiplomatSuitL
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
  #inhand:
  #  - BriefcaseIAAFilled




- type: entity
  id: SpawnMagistrat
  parent: SpawnPointJobBase
  name: magistrat spawn
  components:
    - type: SpawnPoint
      job_id: Magistrat
    - type: Sprite
      layers:
        - state: green
        - state: hop



- type: entity
  parent: BasePDA
  id: MagistratPDA
  name: magistrat PDA
  description: magistrat PDA
  components:
  - type: Pda
    id: MagistratIDCard
    state: pda-lawyer
  - type: Icon
    state: pda-lawyer

- type: entity
  parent: IDCardStandard
  id: MagistratIDCard
  name: magistrat ID card
  description: magistrat ID card
  components:
    - type: Sprite
      layers:
        - state: default
        - state: idlawyer
    - type: PresetIdCard
      job: Magistrat





