- type: entity
  parent: ClothingBackpackERTSecurity
  id: ClothingBackpackADTBlueShieldOfficerFilled
  components:
    - type: Storage
      maxItemSize: Huge
      grid:
      - 0,0,6,4
    - type: StorageFill
      contents:
        - id: Zipties
          amount: 3
        - id: ADTPowerCellLasgunRevolver
          amount: 2
        - id: WeaponDisabler
        - id: Stunbaton
        - id: BoxSurvivalSecurity
        - id: BlueShieldsuit
        - id: SpaceCash1000
    - type: Sprite
      sprite: ADT/Clothing/Back/blueshield_backpack.rsi

