- type: entity
  noSpawn: true
  parent: ClothingBackpackERTSecurity
  id: ClothingBackpackADTBlueShieldOfficerFilled
  components:
    - type: Storage
      maxItemSize: Huge
      maxTotalWeight: 9000
    - type: StorageFill
      contents:
        - id: MedkitBruteFilled
        - id: Zipties
        - id: Zipties
        #- id: Zipties
        #- id: WeaponDisabler
        - id: Stunbaton
        - id: HandheldCrewMonitor
        - id: MagazinePistolSubMachineGun
        - id: MagazinePistolSubMachineGun
        - id: MagazinePistolSubMachineGunRubber
        - id: MagazinePistolSubMachineGunRubber
        #- id: WeaponSubMachineGunDrozdRubber
        #- id: WeaponPulsePistol
        #- id: GrenadeFlashBang
        #- id: GrenadeFlashBang
        #- id: GrenadeFlashBang
        #- id: BoxSurvivalSecurity
        #- id: BlueShieldBox
        - id: BlueShieldsuit
        - id: OxygenTankFilled
    - type: Sprite
      sprite: ADT/Clothing/Back/blueshield_backpack.rsi

