- type: job
  id: ADTBlueShieldOfficer
  name: job-name-ADTBlueShieldOfficer
  description: job-description-ADTBlueShieldOfficer
  playTimeTracker: JobADTBlueShieldOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 54000
    - !type:RoleTimeRequirement
      role: JobParamedic
      time: 25200
  startingGear: ADTBlueShieldOfficerGear
  icon: "JobIconADTBlueShieldOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
    - Command
    - Brig
    - Security
    - Armory
    - Maintenance
    - Service
    - External
    - Research
    - Medical
    - Engineering
    - Cargo
    - Centcom
    - BlueShield
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: playTimeTracker
  id: JobADTBlueShieldOfficer

- type: startingGear
  id: ADTBlueShieldOfficerGear
  equipment:
    head: ADTClothingHeadHatBeretBlueshield
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetCentCom
    mask: ClothingMaskGasSecurity
    jumpsuit: ClothingUniformJumpsuitNanotrasen
    back: ClothingBackpackADTBlueShieldOfficerFilled
    shoes: ClothingShoesBootsCombatFilled
    outerClothing: ADTClothingBlueshieldArmor
    belt: ClothingBeltMilitaryWebbingBlueShieldFilled
    gloves: ClothingHandsGlovesCombat
    id: ADTBlueShieldOfficerPDA
    pocket1: ADTWeaponPistolBlueShitX02
    pocket2: HandheldCrewMonitor
    underwearb: ADTClothingUnderwearBottomBoxersBlueshield # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
    neck: ClothingNeckCloakNanotrasen
  underweart: ADTClothingUnderwearTopBraBlueshield # Sirena-Underwear
  underwearb: ADTClothingUnderwearBottomPantiesBlueshield # Sirena-Underwear

- type: entity
  id: SpawnADTBlueShieldOfficer
  parent: SpawnPointJobBase
  name: ADTBlueShieldOfficer
  components:
    - type: SpawnPoint
      job_id: ADTBlueShieldOfficer
    - type: Sprite
      layers:
        - state: green
        - state: hop

- type: entity
  parent: BasePDA
  id: ADTBlueShieldOfficerPDA
  name: BlueShield PDA
  description: Это пахнет защитой.
  components:
    - type: Pda
      id: ADTBlueShieldOfficerIDCard
      state: pda-ert
    - type: PdaBorderColor
      borderColor: "#A32D26"
      accentVColor: "#447987"
    - type: Icon
      state: pda-ert
    - type: HealthAnalyzer
      scanDelay: 1.2

- type: entity
  parent: IDCardStandard
  id: ADTBlueShieldOfficerIDCard
  name: Blue Shield Officer ID card
  components:
    - type: Sprite
      layers:
        - state: default
        - state: ert_security
    - type: PresetIdCard
      job: ADTBlueShieldOfficer
