- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  canBeAntag: false
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerclothingskirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
