- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ADTServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Maintenance
  - Bar
  - Kitchen
  extendedAccess:
  - Hydroponics

- type: startingGear
  id: ServiceWorkerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBartender
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraWhite # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtBartender
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
