- type: job
  id: ADTPathologist
  name: job-name-ADTPathologist
  description: job-description-ADTPathologist
  playTimeTracker: JobADTPathologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 #6 hrs
  startingGear: ADTPathologistGear
  icon: "JobIconADTPathologist"
  supervisors: job-supervisors-cmo
  canBeAntag: true
  access:
    - Medical
    - Maintenance

- type: startingGear
  id: ADTPathologistGear
  equipment:
    jumpsuit: ADTClothingUniformPathologistSuit
    back: ADTClothingBackpackPathologistFilled
    shoes: ClothingShoesColorWhite
    id: ADTPathologistPDA
    ears: ClothingHeadsetMedical
    belt: BoxFolderClipboard
    pocket1: ADTObjectsSpecificFormalinChemistryBottle
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
  underweart: ClothingUnderwearTopBraSportsAlternative # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerclothingskirt: ADTClothingUniformPathologistSuit
  satchel: ADTClothingBackpackSatchelPathologistFilled
  duffelbag: ADTClothingBackpackDuffelPathologistFilled